In [1]:
!ls

03_00_0_teoria.ipynb                    03_03_Operations_in_Pandas.ipynb
03_00_API.ipynb                         Caso_Practico.ipynb
03_00_csv.ipynb                         data
03_01_Introducing_Pandas_Objects.ipynb  prueba.ipynb
03_02_Data_Indexing_and_Selection.ipynb

In [7]:
!ls data/

03_03_Operations_in_Pandas.ipynb prueba.csv
alllines.txt                     telefonia.tsv
countries.csv                    ventas_comercial
empresas.csv

# Ventas Comercial

In [42]:
import pandas as pd

In [71]:
def leer_ins(path):
    filenames = glob.glob(path + "/*.csv")
    dataframes = {}
    for file in filenames:
        dataframes[file.split(' ')[-1].replace('.csv', '')] = pd.read_csv(file)
    return dataframes
leer_ins(directorio)

{'John':       Unnamed: 0  Dataline       Play  PlayerLinenumber ActSceneLine  \
 0          43490     43491  King John              11.0       5.5.97
 1          43491     43492  King John              11.0       5.5.97
 2          43492     43493  King John              11.0          NaN
 3          43493     43494  King John               1.0        1.1.1
 4          43494     43495  King John               2.0        1.1.2
 ...          ...       ...        ...               ...          ...
 2761       46251     46252  King John              26.0      5.7.120
 2762       46252     46253  King John              26.0      5.7.121
 2763       46253     46254  King John              26.0      5.7.122
 2764       46254     46255  King John              26.0      5.7.123
 2765       46255     46256  King John              26.0          NaN

                Player                                         PlayerLine
 0     KING HENRY VIII                                              ACT I
 1     KING HENRY VIII                       SCENE I. KING JOHN'S palace.
 2     KING HENRY VIII  Enter KING JOHN, QUEEN ELINOR, PEMBROKE, ESSEX...
 3           KING JOHN    Now, say, Chatillon, what would France with us?
 4           CHATILLON    Thus, after greeting, speaks the King of France
 ...               ...                                                ...
 2761          BASTARD         Now these her princes are come home again,
 2762          BASTARD       Come the three corners of the world in arms,
 2763          BASTARD  And we shall shock them. Nought shall make us ...
 2764          BASTARD             If England to itself do rest but true.
 2765          BASTARD                                             Exeunt

 [2766 rows x 7 columns],
 'VIII':       Unnamed: 0  Dataline        Play  PlayerLinenumber ActSceneLine  \
 0          40071     40072  Henry VIII              83.0          NaN
 1          40072     40073  Henry VIII              83.0          NaN
 2          40073     40074  Henry VIII              83.0        1.0.1
 3          40074     40075  Henry VIII              83.0        1.0.2
 4          40075     40076  Henry VIII              83.0        1.0.3
 ...          ...       ...         ...               ...          ...
 3414       43485     43486  Henry VIII              11.0       5.5.93
 3415       43486     43487  Henry VIII              11.0       5.5.94
 3416       43487     43488  Henry VIII              11.0       5.5.95
 3417       43488     43489  Henry VIII              11.0       5.5.96
 3418       43489     43490  Henry VIII              11.0       5.5.97

                Player                                      PlayerLine
 0              Chorus                                           ACT I
 1              Chorus                                        PROLOGUE
 2              Chorus   I come no more to make you laugh: things now,
 3              Chorus         That bear a weighty and a serious brow,
 4              Chorus  Sad, high, and working, full of state and woe,
 ...               ...                                             ...
 3414  KING HENRY VIII        The merciful construction of good women,
 3415  KING HENRY VIII    For such a one we show'd 'em: if they smile,
 3416  KING HENRY VIII       And say 'twill do, I know, within a while
 3417  KING HENRY VIII    All the best men are ours, for 'tis ill hap,
 3418  KING HENRY VIII    If they hold when their ladies bid 'em clap.

 [3419 rows x 7 columns],
 '2':       Unnamed: 0  Dataline             Play  PlayerLinenumber ActSceneLine  \
 0           6188      6189  Henry VI Part 2              13.0          NaN
 1           6189      6190  Henry VI Part 2              13.0          NaN
 2           6190      6191  Henry VI Part 2              13.0          NaN
 3           6191      6192  Henry VI Part 2               1.0        1.1.1
 4           6192      6193  Henry VI Part 2               1.0        1.1.2
 ...          ...       ...              ...               ...          ...
 3329        9517      9518  Henry VI Part 2               5.0       5.3.31
 3330        9518      9519  Henry VI Part 2               5.0       5.3.32
 3331        9519      9520  Henry VI Part 2               5.0       5.3.33
 3332        9520      9521  Henry VI Part 2               5.0       5.3.34
 3333        9521      9522  Henry VI Part 2               5.0          NaN

        Player                                         PlayerLine
 0     SUFFOLK                                              ACT I
 1     SUFFOLK                       SCENE I. London. The palace.
 2     SUFFOLK  Flourish of trumpets: then hautboys. Enter KIN...
 3     SUFFOLK                   As by your high imperial majesty
 4     SUFFOLK           I had in charge at my depart for France,
 ...       ...                                                ...
 3329  WARWICK            Saint Alban's battle won by famous York
 3330  WARWICK             Shall be eternized in all age to come.
 3331  WARWICK       Sound drums and trumpets, and to London all:
 3332  WARWICK          And more such days as these to us befall!
 3333  WARWICK                                             Exeunt

 [3334 rows x 7 columns],
 'Errors':       Unnamed: 0  Dataline                Play  PlayerLinenumber ActSceneLine  \
 0          22427     22428  A Comedy of Errors             132.0          NaN
 1          22428     22429  A Comedy of Errors             132.0          NaN
 2          22429     22430  A Comedy of Errors             132.0          NaN
 3          22430     22431  A Comedy of Errors               1.0        1.1.1
 4          22431     22432  A Comedy of Errors               1.0        1.1.2
 ...          ...       ...                 ...               ...          ...
 2050       24477     24478  A Comedy of Errors             140.0      5.1.453
 2051       24478     24479  A Comedy of Errors             141.0      5.1.454
 2052       24479     24480  A Comedy of Errors             141.0      5.1.455
 2053       24480     24481  A Comedy of Errors             141.0      5.1.456
 2054       24481     24482  A Comedy of Errors             141.0          NaN

                   Player                                         PlayerLine
 0        OCTAVIUS CAESAR                                              ACT I
 1        OCTAVIUS CAESAR          SCENE I. A hall in DUKE SOLINUS'S palace.
 2        OCTAVIUS CAESAR  Enter DUKE SOLINUS, AEGEON, Gaoler, Officers, ...
 3                 AEGEON               Proceed, Solinus, to procure my fall
 4                 AEGEON         And by the doom of death end woes and all.
 ...                  ...                                                ...
 2050  DROMIO OF SYRACUSE  We'll draw cuts for the senior: till then lead...
 2051   DROMIO OF EPHESUS                                   Nay, then, thus:
 2052   DROMIO OF EPHESUS   We came into the world like brother and brother,
 2053   DROMIO OF EPHESUS  And now let's go hand in hand, not one before ...
 2054   DROMIO OF EPHESUS                                             Exeunt

 [2055 rows x 7 columns],
 '3':       Unnamed: 0  Dataline             Play  PlayerLinenumber ActSceneLine  \
 0           9522      9523  Henry VI Part 3               5.0          NaN
 1           9523      9524  Henry VI Part 3               5.0          NaN
 2           9524      9525  Henry VI Part 3               5.0          NaN
 3           9525      9526  Henry VI Part 3               1.0        1.1.1
 4           9526      9527  Henry VI Part 3               2.0        1.1.2
 ...          ...       ...              ...               ...          ...
 3133       12655     12656  Henry VI Part 3               9.0       5.7.42
 3134       12656     12657  Henry VI Part 3               9.0       5.7.43
 3135       12657     12658  Henry VI Part 3               9.0       5.7.44
 3136       12658     12659  Henry VI Part 3               9.0       5.7.45
 3137       12659     12660  Henry VI Part 3               9.0          NaN

               Player                                         PlayerLine
 0            WARWICK                                              ACT I
 1            WARWICK             SCENE I. London. The Parliament-house.
 2            WARWICK  Alarum. Enter YORK, EDWARD, RICHARD, NORFOLK, ...
 3            WARWICK           I wonder how the king escaped our hands.
 4               YORK        While we pursued the horsemen of the north,
 ...              ...                                                ...
 3133  KING EDWARD IV       With stately triumphs, mirthful comic shows,
 3134  KING EDWARD IV          Such as befits the pleasure of the court?
 3135  KING EDWARD IV     Sound drums and trumpets! farewell sour annoy!
 3136  KING EDWARD IV          For here, I hope, begins our lasting joy.
 3137  KING EDWARD IV                                             Exeunt

 [3138 rows x 7 columns],
 'Athens':       Unnamed: 0  Dataline             Play  PlayerLinenumber ActSceneLine  \
 0          93803     93804  Timon of Athens              78.0      5.1.383
 1          93804     93805  Timon of Athens              78.0      5.1.383
 2          93805     93806  Timon of Athens              78.0          NaN
 3          93806     93807  Timon of Athens               1.0        1.1.1
 4          93807     93808  Timon of Athens               2.0        1.1.2
 ...          ...       ...              ...               ...          ...
 2657       96460     96461  Timon of Athens              14.0       5.4.97
 2658       96461     96462  Timon of Athens              14.0       5.4.98
 2659       96462     96463  Timon of Athens              14.0       5.4.99
 2660       96463     96464  Timon of Athens              14.0      5.4.100
 2661       96464     96465  Timon of Athens              14.0          NaN

           Player                                         PlayerLine
 0       PROSPERO                                              ACT I
 1       PROSPERO          SCENE I. Athens. A hall in Timon's house.
 2       PROSPERO  Enter Poet, Painter, Jeweller, Merchant, and o...
 3           Poet                                     Good day, sir.
 4        Painter                             I am glad you're well.
 ...          ...                                                ...
 2657  ALCIBIADES            And I will use the olive with my sword,
 2658  ALCIBIADES  Make war breed peace, make peace stint war, ma...
 2659  ALCIBIADES          Prescribe to other as each other's leech.
 2660  ALCIBIADES                              Let our drums strike.
 2661  ALCIBIADES                                             Exeunt

 [2662 rows x 7 columns],
 'Tale':       Unnamed: 0  Dataline            Play  PlayerLinenumber ActSceneLine  \
 0         107907    107908  A Winters Tale              52.0          NaN
 1         107908    107909  A Winters Tale              52.0          NaN
 2         107909    107910  A Winters Tale              52.0          NaN
 3         107910    107911  A Winters Tale               1.0        1.1.1
 4         107911    107912  A Winters Tale               1.0        1.1.2
 ...          ...       ...             ...               ...          ...
 3484      111391    111392  A Winters Tale              38.0      5.3.180
 3485      111392    111393  A Winters Tale              38.0      5.3.181
 3486      111393    111394  A Winters Tale              38.0      5.3.182
 3487      111394    111395  A Winters Tale              38.0      5.3.183
 3488      111395    111396  A Winters Tale              38.0          NaN

           Player                                         PlayerLine
 0      VALENTINE                                              ACT I
 1      VALENTINE           SCENE I. Antechamber in LEONTES' palace.
 2      VALENTINE                       Enter CAMILLO and ARCHIDAMUS
 3     ARCHIDAMUS  If you shall chance, Camillo, to visit Bohemia...
 4     ARCHIDAMUS   the like occasion whereon my services are now on
 ...          ...                                                ...
 3484     LEONTES         Lead us from hence, where we may leisurely
 3485     LEONTES              Each one demand an answer to his part
 3486     LEONTES     Perform'd in this wide gap of time since first
 3487     LEONTES             We were dissever'd: hastily lead away.
 3488     LEONTES                                             Exeunt

 [3489 rows x 7 columns],
 '1':       Unnamed: 0  Dataline             Play  PlayerLinenumber ActSceneLine  \
 0           3205      3206  Henry VI Part 1               8.0          NaN
 1           3206      3207  Henry VI Part 1               8.0          NaN
 2           3207      3208  Henry VI Part 1               8.0          NaN
 3           3208      3209  Henry VI Part 1               1.0        1.1.1
 4           3209      3210  Henry VI Part 1               1.0        1.1.2
 ...          ...       ...              ...               ...          ...
 2978        6183      6184  Henry VI Part 1              13.0      5.5.105
 2979        6184      6185  Henry VI Part 1              13.0      5.5.106
 2980        6185      6186  Henry VI Part 1              13.0      5.5.107
 2981        6186      6187  Henry VI Part 1              13.0      5.5.108
 2982        6187      6188  Henry VI Part 1              13.0          NaN

              Player                                         PlayerLine
 0     KING HENRY IV                                              ACT I
 1     KING HENRY IV                        SCENE I. Westminster Abbey.
 2     KING HENRY IV  Dead March. Enter the Funeral of KING HENRY th...
 3           BEDFORD  Hung be the heavens with black, yield day to n...
 4           BEDFORD      Comets, importing change of times and states,
 ...             ...                                                ...
 2978        SUFFOLK          With hope to find the like event in love,
 2979        SUFFOLK            But prosper better than the Trojan did.
 2980        SUFFOLK    Margaret shall now be queen, and rule the king,
 2981        SUFFOLK      But I will rule both her, the king and realm.
 2982        SUFFOLK                                               Exit

 [2983 rows x 7 columns],
 'III':       Unnamed: 0  Dataline         Play  PlayerLinenumber ActSceneLine  \
 0          81340     81341  Richard III              11.0          NaN
 1          81341     81342  Richard III              11.0          NaN
 2          81342     81343  Richard III              11.0          NaN
 3          81343     81344  Richard III               1.0        1.1.1
 4          81344     81345  Richard III               1.0        1.1.2
 ...          ...       ...          ...               ...          ...
 3936       85276     85277  Richard III               7.0       5.5.38
 3937       85277     85278  Richard III               7.0       5.5.39
 3938       85278     85279  Richard III               7.0       5.5.40
 3939       85279     85280  Richard III               7.0       5.5.41
 3940       85280     85281  Richard III               7.0          NaN

                  Player                                         PlayerLine
 0     HENRY BOLINGBROKE                                              ACT I
 1     HENRY BOLINGBROKE                         SCENE I. London. A street.
 2     HENRY BOLINGBROKE                            Enter GLOUCESTER, solus
 3            GLOUCESTER                Now is the winter of our discontent
 4            GLOUCESTER          Made glorious summer by this sun of York,
 ...                 ...                                                ...
 3936           RICHMOND    Let them not live to taste this land's increase
 3937           RICHMOND  That would with treason wound this fair land's...
 3938           RICHMOND   Now civil wounds are stopp'd, peace lives again:
 3939           RICHMOND         That she may long live here, God say amen!
 3940           RICHMOND                                             Exeunt

 [3941 rows x 7 columns],
 'data/ventas_comercial/Hamlet':       Unnamed: 0  Dataline    Play  PlayerLinenumber ActSceneLine  \
 0          32432     32433  Hamlet             138.0          NaN
 1          32433     32434  Hamlet             138.0          NaN
 2          32434     32435  Hamlet             138.0          NaN
 3          32435     32436  Hamlet               1.0        1.1.1
 4          32436     32437  Hamlet               2.0        1.1.2
 ...          ...       ...     ...               ...          ...
 4239       36671     36672  Hamlet             147.0      5.2.421
 4240       36672     36673  Hamlet             147.0      5.2.422
 4241       36673     36674  Hamlet             147.0      5.2.423
 4242       36674     36675  Hamlet             147.0      5.2.424
 4243       36675     36676  Hamlet             147.0      5.2.424

                  Player                                         PlayerLine
 0             CYMBELINE                                              ACT I
 1             CYMBELINE   SCENE I. Elsinore. A platform before the castle.
 2             CYMBELINE       FRANCISCO at his post. Enter to him BERNARDO
 3              BERNARDO                                       Who's there?
 4             FRANCISCO        Nay, answer me: stand, and unfold yourself.
 ...                 ...                                                ...
 4239  PRINCE FORTINBRAS                              Speak loudly for him.
 4240  PRINCE FORTINBRAS           Take up the bodies: such a sight as this
 4241  PRINCE FORTINBRAS      Becomes the field, but here shows much amiss.
 4242  PRINCE FORTINBRAS                        Go, bid the soldiers shoot.
 4243  PRINCE FORTINBRAS  A dead march. Exeunt, bearing off the dead bod...

 [4244 rows x 7 columns],
 'Juliet':       Unnamed: 0  Dataline              Play  PlayerLinenumber ActSceneLine  \
 0          85281     85282  Romeo and Juliet               7.0          NaN
 1          85282     85283  Romeo and Juliet               7.0          NaN
 2          85283     85284  Romeo and Juliet               7.0        1.0.1
 3          85284     85285  Romeo and Juliet               7.0        1.0.2
 4          85285     85286  Romeo and Juliet               7.0        1.0.3
 ...          ...       ...               ...               ...          ...
 3308       88589     88590  Romeo and Juliet              65.0      5.3.318
 3309       88590     88591  Romeo and Juliet              65.0      5.3.319
 3310       88591     88592  Romeo and Juliet              65.0      5.3.320
 3311       88592     88593  Romeo and Juliet              65.0      5.3.321
 3312       88593     88594  Romeo and Juliet              65.0          NaN

         Player                                        PlayerLine
 0     RICHMOND                                             ACT I
 1     RICHMOND                                          PROLOGUE
 2     RICHMOND            Two households, both alike in dignity,
 3     RICHMOND           In fair Verona, where we lay our scene,
 4     RICHMOND          From ancient grudge break to new mutiny,
 ...        ...                                               ...
 3308    PRINCE  Go hence, to have more talk of these sad things,
 3309    PRINCE        Some shall be pardon'd, and some punished:
 3310    PRINCE                 For never was a story of more woe
 3311    PRINCE                Than this of Juliet and her Romeo.
 3312    PRINCE                                            Exeunt

 [3313 rows x 7 columns],
 'Shrew':       Unnamed: 0  Dataline                 Play  PlayerLinenumber  \
 0          88594     88595  Taming of the Shrew              65.0
 1          88595     88596  Taming of the Shrew              65.0
 2          88596     88597  Taming of the Shrew               1.0

# Allines

In [38]:
import pandas as pd

In [39]:
path_allines = "data/alllines.txt"

In [40]:
allines = pd.read_csv(path_allines, sep = " ")

In [41]:
print("The poem starts like this: ")
allines.head()

The poem starts like this:

                                               ACT I
0                       SCENE I. London. The palace.
1  Enter KING HENRY, LORD JOHN OF LANCASTER, the ...
2             So shaken as we are, so wan with care,
3         Find we a time for frighted peace to pant,
4     And breathe short-winded accents of new broils

In [16]:
allines.describe()

         ACT I
count   111395
unique  107580
top       Exit
freq       564

In [17]:
type(allines)

pandas.core.frame.DataFrame

In [18]:
"The poem Alllines has " + str(len(allines)) + " rows"

'The poem Alllines has 111395 rows'

# Empresas

In [19]:
import pandas as pd

In [20]:
path_empresas = "data/empresas.csv"

In [21]:
empresas = pd.read_csv(path_empresas)

In [61]:
print("The tree top companies are: ")
empresas['Title'].head(3)

The tree top companies are:

0               Walmart
1    Berkshire Hathaway
2                 Apple
Name: Title, dtype: object

In [65]:
"Average number of employees per company " + str(empresas["Employees"].mean())

'Average number of employees per company 56350.132'

In [24]:
sector_filter = empresas["Sector"].str.contains("Food")
empresas[sector_filter]

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
16,17,Walgreens Boots Alliance,http://www.walgreensbootsalliance.com,300000,Food & Drug Stores,Food and Drug Stores,"Deerfield, IL",108 Wilmot Rd.,Deerfield,IL,...,"President, Chief Executive Officer & Director","108 Wilmot Rd., Deerfield, IL 60015",WBA,"Walgreens Boots Alliance, Inc",117351,13.4,4173.0,-1.1,72688,29880.0
17,18,Kroger,http://www.thekrogerco.com,443000,Food & Drug Stores,Food and Drug Stores,"Cincinnati, OH",1014 Vine St.,Cincinnati,OH,...,Chairman & Chief Executive Officer,"1014 Vine St., Cincinnati, OH 45202",KR,The Kroger Company,115337,5.0,1975.0,-3.1,36505,6698.0
43,44,PepsiCo,http://www.pepsico.com,264000,"Food, Beverages & Tobacco",Food Consumer Products,"Purchase, NY",700 Anderson Hill Rd.,Purchase,NY,...,Chairman & Chief Executive Officer,"700 Anderson Hill Rd., Purchase, NY 10577",PEP,"PepsiCo, Inc.",62799,-0.4,6329.0,16.1,74129,11095.0
44,45,Archer Daniels Midland,http://www.adm.com,31800,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",77 W. Wacker Dr.,Chicago,IL,...,"Chairman, President & Chief Executive Officer","77 W. Wacker Dr., Chicago, IL 60601",ADM,Archer-Daniels-Midland Company,62346,-7.9,1279.0,-30.8,39769,17173.0
48,49,Albertsons Cos.,http://www.albertsons.com,274000,Food & Drug Stores,Food and Drug Stores,"Boise, ID",250 Parkcenter Blvd.,Boise,ID,...,Chairman & Chief Executive Officer,"250 Parkcenter Blvd., Boise, ID 83706",PRU,"Albertsons Companies, Inc.",58734,115.9,-502.2,-22.6,23770,1613.0
63,64,Coca-Cola,http://www.coca-colacompany.com,100300,"Food, Beverages & Tobacco",Beverages,"Atlanta, GA",1 Coca-Cola Plaza,Atlanta,GA,...,"President, Chief Executive Officer & Director","1 Coca-Cola Plaza, Atlanta, GA 30313",KO,The Coca-Cola Company,41863,-5.5,6527.0,-11.2,87270,23062.0
81,82,Tyson Foods,http://www.tysonfoods.com,114000,"Food, Beverages & Tobacco",Food Production,"Springdale, AR",2200 W. Don Tyson Pkwy.,Springdale,AR,...,"President, Chief Executive Officer & Director","2200 W. Don Tyson Pkwy., Springdale, AR 72762",TSN,"Tyson Foods, Inc.",36881,-10.9,1768.0,44.9,22373,9608.0
84,85,Publix Super Markets,http://www.publix.com,191000,Food & Drug Stores,Food and Drug Stores,"Lakeland, FL",3300 Publix Corporate Pkwy.,Lakeland,FL,...,"President, Chief Executive Officer & Director","3300 Publix Corporate Pkwy., Lakeland, FL 33811",ALL,"Publix Super Markets, Inc.",34274,5.1,2025.7,3.1,17464,13473.0
90,91,Rite Aid,http://www.riteaid.com,70580,Food & Drug Stores,Food and Drug Stores,"Camp Hill, PA",30 Hunter Lane,Camp Hill,PA,...,Chairman & Chief Executive Officer,"30 Hunter Lane, Camp Hill, PA 17011",RAD,Rite Aid Corporation,30737,15.9,165.5,-92.2,11277,581.0
92,93,CHS,http://www.chsinc.com,12157,"Food, Beverages & Tobacco",Food Production,"Inver Grove Heights, MN",5500 Cenex Dr.,Inver Grove Heights,MN,...,"President, Chief Executive Officer & Director","5500 Cenex Dr., Inver Grove Heights, MN 55077",GILD,CHS Inc.,30347,-12.2,424.2,-45.7,17318,7852.0
103,104,Philip Morris International,http://www.pmi.com,79500,"Food, Beverages & Tobacco",Tobacco,"New York, NY",120 Park Ave.,New York,NY,...,Chief Executive Officer & Director,"120 Park Ave., New York, NY 10017",PM,Philip Morris International Inc.,26685,-0.4,6967.0,1.4,36851,-12688.0
105,106,Kraft Heinz,http://www.kraftheinzcompany.com,41000,"Food, Beverages & Tobacco",Food Consumer Products,"Pittsburgh, PA",1 PPG Place,Pittsburgh,PA,...,Chief Executive Officer & Director,"1 PPG Place, Pittsburgh, PA 15222",KHC,The Kraft Heinz Company,26487,44.4,3632.0,472.9,120480,57358.0
108,109,Mondelez International,http://www.mondelezinternational.com,90000,"Food, Beverages & Tobacco",Food Consumer Products,"Deerfield, IL",3 Pkwy. N.,Deerfield,IL,...,Chairman & Chief Executive Officer,"3 Pkwy. N., Deerfield, IL 60015",MDLZ,"Mondelez International, Inc.",25923,-12.5,1659.0,-77.2,61538,25161.0
147,148,Altria Group,http://www.altria.com,8300,"Food, Beverages & Tobacco",Tobacco,"Richmond, VA",6601 W. Broad St.,Richmond,VA,...,"Chairman, President & Chief Executive Officer","6601 W. Broad St., Richmond, VA 23230",MO,"Altria Group, Inc.",19337,2.6,14239.0,171.7,45932,12770.0
157,158,Supervalu,http://www.supervalu.com,38000,Food & Drug Stores,Food and Drug Stores,"Eden Prairie, MN",11840 Valley View Rd.,Eden Prairie,MN,...,"President, Chief Executive Officer & Director","11840 Valley View Rd., Eden Prairie, MN 55344",SVU,Supervalu Inc.,17529,-1.6,178.0,-7.3,4370,-441.0
164,165,General Mills,http://www.generalmills.com,39000,"Food, Beverages & Tobacco",Food Consumer Products,"Minneapolis, MN",1 General Mills Blvd.,Minneapolis,MN,...,Chief Executive Officer & Director,"1 General Mills Blvd., Minneapolis, MN 55426",GIS,"General Mills, Inc.",16563,-6.1,1697.4,39,21712,4930.0
175,176,Whole Foods Market,http://www.wholefoodsmarket.com,73515,Food & Drug Stores,Food and Drug Stores,"Austin, TX",550 Bowie St.,Austin,TX,...,Chief Executive Officer & Director,"550 Bowie St., Austin, TX 78703",WFM,"Whole Foods Market, Inc.",15724,2.2,507.0,-5.4,6341,3224.0
196,197,Conagra Brands,http://www.conagrabrands.com,20900,"Food, Beverages & Tobacco",Food Consumer Products,"Chicago, IL",222 W. Merchandise Mart Plaza,Chicago,IL,...,"President, Chief Executive Officer & Director","222 W. Merchandise Mart Plaza, Chicago, IL 60654",CAG,"Conagra Brands, Inc.",14134,-10.8,-677.0,"-1,168.70",13391,3714.0
208,209,Land O’Lakes,http://www.landolakesinc.com,10000,"Food, Beverages & Tobacco",Food Consumer Products,"Arden Hills, MN",4001 Lexington Ave. N.,Arden Hills,MN,...,"President, Chief Executive Officer & Director","4001 Lexington Ave. N., Arden Hills, MN 55126",NWL,"Land O'Lakes, Inc.",13233,0.6,244.9,-20.4,8305,1904.0
215,216,Kellogg,http://www.kelloggcompany.com,37369,"Food, Beverages & Tobacco",Food Consumer Products,"Battle Creek, MI",1 Kellogg Sq.,Battle Creek,MI,...,Chairman & Chief Executive Officer,"1 Kellogg Sq., Battle Creek, MI 49017",K,Kellogg Company,13014,-3.8,694.0,13,15111,1910.0
222,223,Reynolds American,http://www.reynoldsamerican.com,5525,"Food, Beverages & Tobacco",Tobacco,"Winston-Salem, NC",401 N. Main St.,Winston-Salem,NC,...,"President, Chief Executive Officer & Director","401 N. Main St., Winston-Salem, NC 27101",RAI,Reynolds American Inc.,12503,17.1,6073.0,86.7,51095,21711.0
294,295,Hormel Foods,http://www.hormelfoods.com,21100,"Food, Beverages & Tobacco",Food Consumer Products,"Austin, MN",1 Hormel Place,Austin,MN,...,Chief Executive Officer & Director,"1 Hormel Place, Austin, MN 55912",HRL,Hormel Foods Corporation,9523,2.8,890.1,29.7,6370,4448.0
338,339,Campbell Soup,http://www.campbellsoupcompany.com,16500,"Food, Beverages & Tobacco",Food Consumer Products,"Camden, NJ",1 Campbell Place,Camden,NJ,...,"President, Chief Executive Officer & Director","1 Campbell Place, Camden, NJ 08103",CPB,Campbell Soup Company,7961,-1.5,563.0,-18.5,7837,1525.0
345,346,J.M. Smucker,http://www.jmsmucker.com,6910,"Food, Beverages & Tobacco",Food Consumer Products,"Orrville, OH",1 Strawberry Lane,Orrville,OH,...,"President, Chief Executive Officer & Director","1 Strawberry Lane, Orrville, OH 44667",SJM,The J.M. Smucker Company,7811,37.2,688.7,99.7,15984,7009.0
350,351,Dean Foods,http://www.deanfoods.com,17000,"Food, Beverages & Tobacco",Food Consumer Products,"Dallas, TX",2711 N. Haskell Ave.,Dallas,TX,...,Chief Executive Officer & Director,"2711 N. Haskell Ave., Dallas, TX 75204",DF,Dean Foods Company,7710,-5.1,119.9,-9.4,2606,611.0
368,369,Hershey,http://www.thehersheycompany.com,17140,"Food, Beverages & Tobacco",Food Consumer Products,"Hershey, PA",100 Crystal A Dr.,Hershey,PA,...,"President, Chief Executive Officer & Director","100 Crystal A Dr., Hershey, PA 17033",HSY,The Hershey Company,7440,0.7,720.0,40.4,5524,786.0
407,408,Constellation Brands,http://www.cbrands.com,9000,"Food, Beverages & Tobacco",Beverages,"Victor, NY",207 High Point Dr.,Victor,NY,...,"President, Chief Executive Officer & Director","207 High Point Dr., Victor, NY 14564",STZ,"Constellation Brands, Inc.",6548,8.6,1054.9,25.7,16965,6560.0
415,416,Dr Pepper Snapple Group,http://www.drpeppersnapplegroup.com,20000,"Food, Beverages & Tobacco",Beverages,"Plano, TX",5301 Legacy Dr.,Plano,TX,...,"President, Chief Executive Officer & Director","5301 Legacy Dr., Plano, TX 75024",DPS,"Dr Pepper Snapple Group, Inc.",6440,2.5,847.0,10.9,9791,2134.0
426,427,TreeHouse Foods,http://www.treehousefoods.com,16027,"Food, Beverages & Tobacco",Food Consumer Products,"Oak Brook, IL",2021 Spring Rd.,Oak Brook,IL,...,Chairman & Chief Executive Officer,"2021 Spring Rd., Oak Brook, IL 60523",THS,"TreeHouse Foods, Inc.",6175,92.6,-228.6,-298.9,6546,2503.0
455,456,Ingredion,http://www.ingredion.com,11000,"Food, Beverages & Tobacco",Food Production,"Westchester, IL",5 Westbrook Corporate Center,Westchester,IL,...,"Chairman, President & Chief Executive Officer","5 Westbrook Corporate Center, Westchester, IL ...",INGR,Ingredion Incorporated,5704,1.5,484.9,20.6,5782,2565.0
485,486,Seaboard,http://www.seaboardcorp.com,11781,"Food, Beverages & Tobacco",Food Production,"Merriam, KS",9000 W. 67th St.,Merriam,KS,...,"Chairman, President & Chief Executive Officer","9000 W. 67th St., Merriam, KS 66202",SEB,Seaboard Corporation,5379,-3.8,312.0,82.5,4755,3162.0

In [25]:
"There are " + str(len(empresas["Hqcity"].unique())) + " cities"

'There are 239 cities'

# Telefonia

In [26]:
import pandas as pd

In [27]:
path_telefonia = "data/telefonia.tsv"

In [28]:
telefonia = pd.read_csv(path_telefonia, sep = '\t')

In [29]:
telefonia

,Fecha de respuesta,id,Edad,Customer Value,Probabilidad de Recomendación,¿Por que?,Date of 1st Feedback Call,Resultado del Primer contacto,Descripción detallada del contacto,Fuiste capaz de resolver el inconveniente?,El cliente se encontró satisfecho con el resultado?
0,6/30/19 23:09,1,43,1.0,10.0,buen servicio y buena atención,NaN,NaN,NaN,NaN,NaN
1,6/30/19 22:56,2,75,1.0,10.0,"Eficiencia, amabilidad, rapidez",NaN,NaN,NaN,NaN,NaN
2,6/30/19 22:52,3,23,1.0,10.0,Todo excelente,NaN,NaN,NaN,NaN,NaN
3,6/30/19 22:33,4,71,2.0,10.0,Vienen enseguida y siempre me solucionan el pr...,NaN,NaN,NaN,NaN,NaN
4,6/30/19 22:25,5,64,2.0,9.0,"Cumplió de acuerdo a mis expectativas, horario...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
35821,1/1/19 8:48,32233,63,2.0,10.0,buen servicio,NaN,NaN,NaN,NaN,NaN
35822,1/1/19 3:40,32234,35,2.0,4.0,La falta de compromiso de parte del seguro por...,02/01/2018,No contactado,no es posible establecer contacto con la titul...,No,No
35823,1/1/19 2:04,32235,41,2.0,10.0,Buena atención y rápida solución de problemas,NaN,NaN,NaN,NaN,NaN
35824,1/1/19 1:07,32236,66,1.0,10.0,"Persona muy eficiente,responsable y educado. ,",NaN,NaN,NaN,NaN,NaN
35825,1/1/19 0:47,32237,54,1.0,7.0,Es correcto el servicio,NaN,NaN,NaN,NaN,NaN

In [30]:
"El promedio de la probabilidad de recomendacion de la compañia telefonica fue de " + str(round(telefonia['Probabilidad de Recomendación'].mean(),2))

'El promedio de la probabilidad de recomendacion de la compañia telefonica fue de 8.34'

In [31]:
"Hubieron " + str(len(telefonia[telefonia['Resultado del Primer contacto'] == "Contacto exitoso"]))+ " contactos exitosos"

'Hubieron 2131 contactos exitosos'

In [32]:
"Se resolvieron " + str(len(telefonia[telefonia['Fuiste capaz de resolver el inconveniente?'] == "Sí"])) + " inconvenientes de " + str(len(telefonia)) + " casos"

'Se resolvieron 1860 inconvenientes de 35826 casos'

In [51]:
telefonia.groupby("El cliente se encontró satisfecho con el resultado?").id.count()

El cliente se encontró satisfecho con el resultado?
No     611
Sí    1892
Name: id, dtype: int64